language: csharp
dist: trusty
mono: none
dotnet: 2.0.0
script:
 - npm install
 - npm install -g bower
 - bower install
 - dotnet restore
 - dotnet build
 - npm install -g karma-cli
 - karma start
 - codecov < coverage/cobertura/cobertura-coverage.xml -t codecov-env