language: csharp
dist: trusty
mono: none
dotnet: 2.0.0
script:
 - npm install
 - npm install -g bower
 - bower install
 - dotnet restore
 - dotnet build
 - npm install -g karma-cli
 - npm install -g codecov.io
 - karma start
 - codecov < coverage/cobertura/cobertura-coverage.xml -t 0c1b9f6a-b7e3-4cb0-b560-0028bed4e809